MODEL:
  TYPE: 'ef'
  SIZE: 0
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 16
  EPOCHS: 1
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  # WANDB_RUN_ID: '1ss87sbp'
  # INITIAL_EPOCH: 15


VAL:
  BATCH_SIZE: 16
  DROP_REMAINDER: true
  DET: false

DATASET:
  INPUT_SHAPE: [256, 192, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: 'gs://rangle/tfrecords_foot_small'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: false
  TRAIN_SAMPLES: 48
  VAL_SAMPLES: 48
  

