MODEL:
  TYPE: 'ef'
  SIZE: 0
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 1
  EPOCHS: 10
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  WANDB_RUN_ID: 'trim-firefly-98'
  INITIAL_EPOCH: 3


VAL:
  BATCH_SIZE: 1
  DROP_REMAINDER: true
  DET: false

DATASET:
  INPUT_SHAPE: [256, 192, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: './data/tfrecords_foot_small'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: false
  TRAIN_SAMPLES: 50
  VAL_SAMPLES: 50
  

