MODEL:
  TYPE: 'eflite'
  SIZE: 4
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 256
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  BASE_LR: 0.0003

VAL:
  BATCH_SIZE: 256
  DROP_REMAINDER: true
  DET: false

DATASET:
  INPUT_SHAPE: [224, 224, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: 'gs://rangle/tfrecords_foot'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: true
  HALF_BODY_PROB: 0.5