MODEL:
  TYPE: 'eflite'
  SIZE: 0
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 512
  EPOCHS: 10
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  WANDB_RUN_ID: '1r6pbo9a'
  INITIAL_EPOCH: 6

VAL:
  BATCH_SIZE: 256
  DROP_REMAINDER: true
  DET: false

DATASET:
  INPUT_SHAPE: [224, 224, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: 'gs://rangle/tfrecords_foot'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: true