MODEL:
  TYPE: 'eflite'
  SIZE: 0
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 512
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  WANDB_RUN_ID: '1s438o9s'
  INITIAL_EPOCH: 55

VAL:
  BATCH_SIZE: 512
  DROP_REMAINDER: false
  DET: false

DATASET:
  INPUT_SHAPE: [224, 224, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: 'gs://rangle/tfrecords_foot'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: false
  # HALF_BODY_PROB: 0.5