MODEL:
  TYPE: 'eflite'
  SIZE: 0
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 3
  EPOCHS: 20
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  WANDB_RUN_ID: '32c71734'
  INITIAL_EPOCH: 9

VAL:
  BATCH_SIZE: 3
  DROP_REMAINDER: true
  DET: false

DATASET:
  INPUT_SHAPE: [224, 224, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: 'gs://rangle/tfrecords_foot_small'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: true
  TRAIN_SAMPLES: 50
  VAL_SAMPLES: 50