MODEL:
  TYPE: 'eflite'
  SIZE: 4
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 64
  EPOCHS: 20
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  WANDB_RUN_ID: '24ckgmb5'
  INITIAL_EPOCH: 8

VAL:
  BATCH_SIZE: 64
  DROP_REMAINDER: true
  DET: false

DATASET:
  INPUT_SHAPE: [224, 224, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: 'gs://rangle/tfrecords_foot'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: false