MODEL:
  TYPE: 'evopose'
  GENOTYPE: [
    [ 3, 1, 2, 1 ],
    [ 3, 3, 3, 2 ],
    [ 5, 2, 5, 2 ],
    [ 3, 4, 10, 2 ],
    [ 5, 2, 14, 1 ],
    [ 5, 4, 16, 1 ],
    [ 3, 2, 10, 1 ]
  ]
  LOAD_WEIGHTS: false
  FINAL_KERNEL: 1
  LITE: true
  DROPOUT: false
  QUANTIZATION: true

TRAIN:
  BATCH_SIZE: 256
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  SAVE_META: true

VAL:
  BATCH_SIZE: 256
  DROP_REMAINDER: false
  DET: false

DATASET:
  INPUT_SHAPE: [256, 192, 3]
  OUTPUT_SHAPE: [-1, -1, 23]
  TFRECORDS: 'gs://rangle/tfrecords_foot'
  ANNOT: './data/annotations'
  CACHE: true
  BFLOAT16: false


