MODEL:
  TYPE: 'evopose'
  GENOTYPE: [
    [ 3, 1, 2, 1 ],
    [ 3, 3, 3, 2 ],
    [ 5, 2, 5, 2 ],
    [ 3, 4, 10, 2 ],
    [ 5, 2, 14, 1 ],
    [ 5, 4, 16, 2 ],
    [ 3, 2, 10, 1 ]
  ]
  LOAD_WEIGHTS: false
  FINAL_KERNEL: 1

TRAIN:
  BATCH_SIZE: 64
  EPOCHS: 20
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  SAVE_META: true

VAL:
  BATCH_SIZE: 64
  DROP_REMAINDER: true
  DET: false

DATASET:
  INPUT_SHAPE: [256, 192, 3]
  OUTPUT_SHAPE: [64, 48, 17]
  TFRECORDS: 'gs://rangle/tfrecordsOriginal_small'
  ANNOT: './data/annotations/person_keypoints_val2017.json'
  CACHE: true
  BFLOAT16: false
  TRAIN_SAMPLES: 512
  VAL_SAMPLES: 512


